plugins:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance

AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - "vendor/**/*"
    - "db/**/*"
    - "config/**/*"
    - "bin/**/*"
    - "node_modules/**/*"
    - "tmp/**/*"
    - "log/**/*"
    - "storage/**/*"

# Rails設定
Rails:
  Enabled: true

# よく使う設定の調整
Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"
    - "config/routes.rb"

Layout/LineLength:
  Max: 120
  Exclude:
    - "spec/**/*"

Style/ClassAndModuleChildren:
  Enabled: false

# Windows環境の改行コード問題を無視
Layout/EndOfLine:
  Enabled: false

# メトリクス系の調整
Metrics/AbcSize:
  Max: 20

Metrics/MethodLength:
  Max: 15
  Exclude:
    - "spec/**/*"

RSpec/MultipleExpectations:
  Max: 3

RSpec/ExampleLength:
  Max: 10

RSpec/NestedGroups:
  Max: 4

RSpec/HookArgument:
  EnforcedStyle: each
